# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('number', models.SmallIntegerField()),
            ],
        ),
    ]
